import { expect, test } from '@playwright/test'
import { mkdir, readFile } from 'node:fs/promises'
import { createLegacyActiveExtractorSave } from './rivalFixtures.ts'
import { OUTPOST_STORAGE_KEY } from '../src/persistence/outpostSave.ts'

// One device-sized workflow; browser clock advances the normal production timers.
test('Orbital Siege construction, failure, refresh, recovery and deterministic replay', async ({ page, request }) => {
  test.setTimeout(150_000)
  const evidence = 'artifacts/screenshots/orbital-siege'
  await mkdir(evidence, { recursive: true })
  expect(await (await request.get('/')).text()).toBe(await readFile('dist/index.html', 'utf8'))
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  const raw = JSON.parse(createLegacyActiveExtractorSave())
  raw.outpost.lunarOre = 230
  await page.addInitScript(({ key, save }) => {
    if (!sessionStorage.getItem('siege-seeded')) {
      localStorage.setItem(key, save)
      sessionStorage.setItem('siege-seeded', 'true')
    }
  }, { key: OUTPOST_STORAGE_KEY, save: JSON.stringify(raw) })
  await page.clock.install()
  await page.goto('/')
  await expect(page.locator('main')).toHaveAttribute('data-scene-ready', 'true')
  await page.getByRole('button', { name: 'CONTINUE', exact: true }).tap()
  const main = page.locator('main')
  await expect(main).toHaveAttribute('data-phase', 'landed')
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 2000))
  const beforeOre = Number(await main.getAttribute('data-lunar-ore'))
  const beforeRate = Number(await main.getAttribute('data-operation-rate'))
  await page.getByRole('button', { name: /BUILD ORBITAL PLATFORM/ }).tap()
  await expect(main).toHaveAttribute('data-siege-status', 'constructing')
  expect(Number(await main.getAttribute('data-lunar-ore'))).toBeCloseTo(beforeOre - 60, 0)
  expect(Number(await main.getAttribute('data-operation-rate'))).toBeLessThan(beforeRate)
  await expect(main).toHaveAttribute('data-operation-active-robots', '1')
  await page.clock.runFor(32)
  await page.screenshot({ path: `${evidence}/assembling.png` })
  await page.clock.fastForward(6200)
  await expect(main).toHaveAttribute('data-siege-status', 'command')
  await page.getByRole('button', { name: /PRESERVE MINING/ }).tap()
  await expect(main).toHaveAttribute('data-operation-active-robots', '2')
  await page.clock.fastForward(10000)
  await page.clock.runFor(32)
  await page.screenshot({ path: `${evidence}/drones-inbound.png` })
  await page.clock.fastForward(2000)
  await expect(main).toHaveAttribute('data-siege-waves', '1')
  await page.clock.runFor(32)
  await page.screenshot({ path: `${evidence}/wave-one.png` })
  await page.clock.fastForward(16000)
  await expect(main).toHaveAttribute('data-siege-status', 'damaged')
  await expect(main).toHaveAttribute('data-siege-waves', '3')
  await expect(main).toHaveAttribute('data-siege-damage', '36')
  await page.clock.runFor(32)
  await page.screenshot({ path: `${evidence}/failure.png` })
  await page.clock.resume()
  await page.reload()
  await page.getByRole('button', { name: 'CONTINUE', exact: true }).tap()
  await expect(main).toHaveAttribute('data-siege-status', 'damaged')
  await expect(main).toHaveAttribute('data-siege-health', '16')
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 2000))
  await page.getByRole('button', { name: /REPAIR PLATFORM/ }).tap()
  await expect(main).toHaveAttribute('data-siege-status', 'repairing')
  await page.clock.fastForward(15200)
  await expect(main).toHaveAttribute('data-siege-status', 'operational')
  await expect(main).toHaveAttribute('data-siege-damage', '0')
  await expect(page.getByText('ORBITAL CONTROL ACHIEVED', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /REPLAY ORBITAL SIEGE/ }).tap()
  await page.clock.fastForward(6200)
  await expect(main).toHaveAttribute('data-siege-status', 'command')
  await page.clock.runFor(32)
  await page.screenshot({ path: `${evidence}/command.png` })
  const choices = page.locator('.siege-command .counterstrike-command__copy small')
  expect(await choices.evaluateAll((items) => items.every((item) => item.scrollWidth <= item.clientWidth))).toBe(true)
  await page.getByRole('button', { name: /PRIORITIZE DEFENSE/ }).tap()
  await expect(main).toHaveAttribute('data-operation-active-robots', '0')
  await page.clock.fastForward(28200)
  await expect(main).toHaveAttribute('data-siege-status', 'operational')
  await expect(main).toHaveAttribute('data-siege-health', '85')
  await page.clock.runFor(32)
  await page.screenshot({ path: `${evidence}/orbital-control.png` })
  await page.clock.resume()
  await page.reload()
  await page.getByRole('button', { name: 'CONTINUE', exact: true }).tap()
  await expect(main).toHaveAttribute('data-siege-status', 'operational')
  await expect(main).toHaveAttribute('data-siege-health', '85')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
  // Reset is the existing confirmed reset interaction.
  page.on('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: /RESET PROTOTYPE/ }).tap()
  await expect(main).toHaveAttribute('data-siege-status', 'none')
  expect(await page.evaluate((key) => localStorage.getItem(key), OUTPOST_STORAGE_KEY)).toBeNull()
})
