import { expect, test } from '@playwright/test'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { createAcceptedCounterstrikeSave } from './firstStrikeFixtures.ts'
import { OUTPOST_STORAGE_KEY } from '../src/persistence/outpostSave.ts'

// One portrait workflow on the ordinary production bundle, using its real reducer and timers.
test('Territory Monuments: choices, three waves, repair, claim, reveal replay and reset recovery', async ({ page, request }) => {
  test.setTimeout(150_000)
  const evidence = 'artifacts/screenshots/territory-monuments'
  await mkdir(evidence, { recursive: true })
  expect(await (await request.get('/')).text()).toBe(await readFile('dist/index.html', 'utf8'))
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  const raw = JSON.parse(createAcceptedCounterstrikeSave('FAILURE'))
  raw.outpost.lunarOre = 230
  await page.addInitScript(({ key, save }) => {
    if (!sessionStorage.getItem('territory-seeded')) {
      localStorage.setItem(key, save)
      sessionStorage.setItem('territory-seeded', 'true')
    }
  }, { key: OUTPOST_STORAGE_KEY, save: JSON.stringify(raw) })
  await page.clock.install()
  await page.goto('/')
  const main = page.locator('main')
  const canvas = page.locator('canvas')
  await expect(main).toHaveAttribute('data-scene-ready', 'true')
  await page.getByRole('button', { name: 'CONTINUE', exact: true }).tap()
  await expect(main).toHaveAttribute('data-monument-view', 'true')
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 1000))
  for (const title of ['HELIOS SPIRE', 'CRATER CROWN', 'BASTION OBELISK', 'SIGNAL ARRAY']) {
    await expect(page.getByRole('button', { name: new RegExp(title) })).toBeEnabled()
  }
  expect(await page.locator('.monument-choices > button').evaluateAll(items => items.every(item => item.getBoundingClientRect().bottom < innerHeight - 12))).toBe(true)
  await page.screenshot({ path: `${evidence}/choices.png` })
  const ore = Number(await main.getAttribute('data-lunar-ore'))
  await page.getByRole('button', { name: /CRATER CROWN/ }).tap()
  expect(Number(await main.getAttribute('data-lunar-ore'))).toBeCloseTo(ore - 90, 1)
  await expect(main).toHaveAttribute('data-monument-status', 'constructing')
  await page.clock.fastForward(4200)
  await expect(main).toHaveAttribute('data-monument-status', 'command')
  await page.clock.runFor(32)
  expect(await page.locator('.monument-command button').evaluateAll(items => items.every(item => item.getBoundingClientRect().bottom < innerHeight - 12))).toBe(true)
  await page.screenshot({ path: `${evidence}/command.png` })
  await expect(canvas).toHaveAttribute('data-octogonals-visible', 'true')
  await expect(canvas).toHaveAttribute('data-base-details-visible', 'false')
  const work = await main.getAttribute('data-monument-work')
  await page.clock.fastForward(60000)
  await expect(main).toHaveAttribute('data-monument-work', work!)
  await expect(main).toHaveAttribute('data-monument-waves', '0')
  // Refresh at a pending allocation: elapsed wall time cannot choose an order.
  await page.clock.resume()
  await page.reload()
  await page.getByRole('button', { name: 'CONTINUE', exact: true }).tap()
  await expect(main).toHaveAttribute('data-monument-status', 'command')
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 1000))
  for (let wave = 0; wave < 3; wave++) {
    await expect(page.getByText(`WAVE ${wave + 1} / 3`, { exact: false })).toBeVisible()
    await page.getByRole('button', { name: /PRESERVE PRODUCTION/ }).tap()
    await expect(main).toHaveAttribute('data-operation-active-robots', '2')
    await page.clock.fastForward(3200)
    await page.clock.runFor(32)
    if (wave === 0) await page.screenshot({ path: `${evidence}/wave.png` })
    await page.clock.fastForward(5000)
    await expect(main).toHaveAttribute('data-monument-waves', String(wave + 1))
  }
  await expect(main).toHaveAttribute('data-monument-status', 'damaged')
  await expect(main).toHaveAttribute('data-territory-claimed', 'false')
  await expect(page.getByText(/−30% production · −15% solar energy/)).toBeVisible()
  await page.clock.runFor(32)
  await page.screenshot({ path: `${evidence}/damaged.png` })
  await page.getByRole('button', { name: /REPAIR MONUMENT/ }).tap()
  await page.clock.fastForward(7200)
  await expect(main).toHaveAttribute('data-monument-status', 'repairing')
  const repairingSave = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), OUTPOST_STORAGE_KEY)
  await page.clock.resume()
  await page.reload()
  await page.getByRole('button', { name: 'CONTINUE', exact: true }).tap()
  await expect(main).toHaveAttribute('data-monument-status', 'repairing')
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 1000))
  await page.clock.fastForward(8500)
  await expect(main).toHaveAttribute('data-monument-status', 'complete')
  await expect(main).toHaveAttribute('data-monument-reveal', 'true')
  await page.clock.runFor(3000)
  await page.screenshot({ path: `${evidence}/orbital-reveal.png` })
  await expect(canvas).toHaveAttribute('data-monument-visible', 'true')
  await expect(canvas).toHaveAttribute('data-claim-signal-visible', 'true')
  await expect(canvas).toHaveAttribute('data-scar-visible', 'true')
  await expect(canvas).toHaveAttribute('data-base-details-visible', 'false')
  await expect(canvas).toHaveAttribute('data-octogonals-visible', 'false')
  await page.clock.fastForward(4000)
  await expect(main).toHaveAttribute('data-monument-reveal', 'false')
  const saved = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), OUTPOST_STORAGE_KEY)
  expect(saved.counterstrike).toEqual(repairingSave.counterstrike)
  expect(saved.firstStrike.scar).toEqual(repairingSave.firstStrike.scar)
  expect(saved.outpost.monument).toMatchObject({ kind: 'CRATER_CROWN', anchor: 'impact-scar', status: 'complete', wavesResolved: 3, oreLost: 18, revealSeen: true })
  await page.getByRole('button', { name: 'REPLAY ORBITAL REVEAL' }).tap()
  await page.clock.fastForward(6500)
  const replayed = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), OUTPOST_STORAGE_KEY)
  expect(replayed.outpost.monument).toEqual(saved.outpost.monument)
  expect(replayed.counterstrike).toEqual(saved.counterstrike)
  await page.getByRole('button', { name: 'RETURN TO ORBIT', exact: true }).tap()
  await page.clock.runFor(400)
  await expect(main).toHaveAttribute('data-monument-view', 'false')
  await expect(canvas).toHaveAttribute('data-monument-detail-visible', 'true')
  await expect(canvas).toHaveAttribute('data-base-details-visible', 'false')
  await page.screenshot({ path: `${evidence}/claimed-orbit.png` })
  const metrics = await canvas.evaluate(el => ({ calls: Number(el.dataset.drawCalls), triangles: Number(el.dataset.triangles), geometries: Number(el.dataset.geometries), programs: Number(el.dataset.programs) }))
  expect(metrics.calls).toBeLessThanOrEqual(80)
  expect(metrics.programs).toBeLessThanOrEqual(24)
  await writeFile('artifacts/territory-monuments-metrics.json', JSON.stringify(metrics, null, 2) + '\n')
  await page.clock.resume()
  await page.reload()
  await page.getByRole('button', { name: 'CONTINUE', exact: true }).tap()
  await expect(main).toHaveAttribute('data-territory-claimed', 'true')
  await expect(main).toHaveAttribute('data-monument-reveal', 'false')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const choicesFit = await page.locator('.monument-panel').evaluate(el => el.scrollWidth <= el.clientWidth)
  expect(choicesFit).toBe(true)
  // Existing reset confirmation, followed by a second choice and a defended success.
  page.on('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: /RESET PROTOTYPE/ }).tap()
  await expect(main).toHaveAttribute('data-monument-status', 'none')
  expect(await page.evaluate(key => localStorage.getItem(key), OUTPOST_STORAGE_KEY)).toBeNull()
  await page.evaluate(({ key, save }) => localStorage.setItem(key, save), { key: OUTPOST_STORAGE_KEY, save: JSON.stringify(raw) })
  await page.reload()
  await page.getByRole('button', { name: 'CONTINUE', exact: true }).tap()
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 1000))
  await page.getByRole('button', { name: /HELIOS SPIRE/ }).tap()
  await page.clock.fastForward(4200)
  for (let wave = 0; wave < 3; wave++) {
    await page.getByRole('button', { name: /^1 DEFEND/ }).tap()
    await expect(main).toHaveAttribute('data-operation-active-robots', '0')
    await page.clock.fastForward(8200)
  }
  await page.clock.fastForward(15000)
  await expect(main).toHaveAttribute('data-monument-status', 'complete')
  await expect(main).toHaveAttribute('data-monument-health', '79')
  await expect(main).toHaveAttribute('data-territory-claimed', 'true')
  await page.clock.runFor(2000)
  await page.screenshot({ path: `${evidence}/helios-success.png` })
  expect(errors).toEqual([])
})
