/**
 * The shipped music package as the runtime sees it. `musicManifest.json` is
 * generated by scripts/music/build-web-music.mjs (handoff 9.4) and never
 * edited by hand; this module types the fields the runtime uses and refuses a
 * manifest that disagrees with the locked contract in musicConstants.ts.
 */
import {
  BEATS_PER_BAR,
  BPM,
  GUARD_SECONDS,
  LAYER_IDS,
  LAYER_SPECS,
  LOOP_BARS,
  LOOP_END_SECONDS,
  LOOP_SECONDS,
  LOOP_START_SECONDS,
  STINGER_IDS,
  STINGER_SPECS,
  type AssetId,
  type LayerId,
  type StingerId,
} from './musicConstants.ts'

export interface MusicManifestAsset {
  readonly id: AssetId
  readonly url: string
  readonly sha256: string
  readonly bytes: number
  readonly channels: 1 | 2
  readonly bitrateKbps: number
  /** Guarded frames at 44.1 kHz (content + 0.4 s). */
  readonly frames: number
  readonly durationSeconds: number
  readonly contentStartSeconds: number
  readonly contentEndSeconds: number
}

export interface MusicManifestLoop extends MusicManifestAsset {
  readonly id: LayerId
  readonly loopStartSeconds: number
  readonly loopEndSeconds: number
}

export interface MusicManifestStinger extends MusicManifestAsset {
  readonly id: StingerId
  readonly bars: number
  readonly contentSeconds: number
  readonly syncSeconds: number
  readonly priority: number
}

export interface MusicManifest {
  readonly loops: readonly MusicManifestLoop[]
  readonly stingers: readonly MusicManifestStinger[]
}

export class MusicManifestError extends Error {
  override readonly name = 'MusicManifestError'
}

type Fields = Readonly<Record<string, unknown>>

function record(value: unknown, where: string): Fields {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new MusicManifestError(`${where} is not an object`)
  return value as Fields
}

function number(fields: Fields, key: string, where: string): number {
  const value = fields[key]
  if (typeof value !== 'number' || !Number.isFinite(value)) throw new MusicManifestError(`${where}.${key} is not a number`)
  return value
}

function string(fields: Fields, key: string, where: string): string {
  const value = fields[key]
  if (typeof value !== 'string' || value === '') throw new MusicManifestError(`${where}.${key} is not a string`)
  return value
}

function expect(condition: boolean, message: string): void {
  if (!condition) throw new MusicManifestError(message)
}

const close = (a: number, b: number) => Math.abs(a - b) < 1e-6

function asset(fields: Fields, id: AssetId, where: string, channels: 1 | 2): MusicManifestAsset {
  const url = string(fields, 'url', where)
  expect(url.startsWith('/') && !url.includes('..') && url.endsWith('.mp3'), `${where}.url ${url} is not a root-relative .mp3`)
  expect(fields.channels === channels, `${where}.channels is not ${channels}`)
  const sha256 = string(fields, 'sha256', where)
  expect(/^[0-9a-f]{64}$/.test(sha256), `${where}.sha256 is not a SHA-256`)
  expect(close(number(fields, 'contentStartSeconds', where), GUARD_SECONDS), `${where} content does not start at the 0.2 s guard`)
  return {
    id,
    url,
    sha256,
    bytes: number(fields, 'bytes', where),
    channels,
    bitrateKbps: number(fields, 'bitrateKbps', where),
    frames: number(fields, 'frames', where),
    durationSeconds: number(fields, 'durationSeconds', where),
    contentStartSeconds: number(fields, 'contentStartSeconds', where),
    contentEndSeconds: number(fields, 'contentEndSeconds', where),
  }
}

/** Validates the generated manifest against the runtime's locked contract. */
export function parseMusicManifest(value: unknown): MusicManifest {
  const root = record(value, 'manifest')
  expect(root.schema === 1, 'manifest schema is not 1')
  expect(root.synthetic !== true, 'manifest is a synthetic fixture package')
  expect(root.bpm === BPM && root.beatsPerBar === BEATS_PER_BAR && root.loopBars === LOOP_BARS, 'manifest grid differs from 100 BPM 4/4 16 bars')
  expect(root.loopSeconds === LOOP_SECONDS && root.guardSeconds === GUARD_SECONDS, 'manifest loop or guard length differs')
  const loopList = root.loops
  const stingerList = root.stingers
  expect(Array.isArray(loopList) && Array.isArray(stingerList), 'manifest has no loops or stingers')

  const loops = LAYER_IDS.map((id): MusicManifestLoop => {
    const entry = (loopList as unknown[]).map((item, index) => record(item, `loops[${index}]`)).find((item) => item.id === id)
    if (entry === undefined) throw new MusicManifestError(`manifest has no loop ${id}`)
    const where = `loop ${id}`
    const loopStartSeconds = number(entry, 'loopStartSeconds', where)
    const loopEndSeconds = number(entry, 'loopEndSeconds', where)
    expect(close(loopStartSeconds, LOOP_START_SECONDS) && close(loopEndSeconds, LOOP_END_SECONDS), `${where} loop region is not [0.2, 38.6)`)
    return { ...asset(entry, id, where, LAYER_SPECS[id].channels), id, loopStartSeconds, loopEndSeconds }
  })

  const stingers = STINGER_IDS.map((id): MusicManifestStinger => {
    const entry = (stingerList as unknown[]).map((item, index) => record(item, `stingers[${index}]`)).find((item) => item.id === id)
    if (entry === undefined) throw new MusicManifestError(`manifest has no stinger ${id}`)
    const where = `stinger ${id}`
    const spec = STINGER_SPECS[id]
    const bars = number(entry, 'bars', where)
    const contentSeconds = number(entry, 'contentSeconds', where)
    const syncSeconds = number(entry, 'syncSeconds', where)
    const priority = number(entry, 'priority', where)
    expect(bars === spec.bars && close(contentSeconds, spec.contentSeconds), `${where} length differs from ${spec.bars} bars`)
    expect(close(syncSeconds, spec.syncSeconds), `${where} sync point differs from ${spec.syncSeconds} s`)
    expect(priority === spec.priority, `${where} priority differs from ${spec.priority}`)
    return { ...asset(entry, id, where, spec.channels), id, bars, contentSeconds, syncSeconds, priority }
  })

  return { loops, stingers }
}

export function manifestAsset(manifest: MusicManifest, id: AssetId): MusicManifestAsset {
  const entry = [...manifest.loops, ...manifest.stingers].find((candidate) => candidate.id === id)
  if (entry === undefined) throw new MusicManifestError(`manifest has no asset ${id}`)
  return entry
}

/** Content seconds of an asset: one loop cycle, or the stinger's bars. */
export function contentSecondsOf(id: AssetId): number {
  return (LAYER_IDS as readonly AssetId[]).includes(id) ? LOOP_SECONDS : STINGER_SPECS[id as StingerId].contentSeconds
}
